# Modified https://github.com/actions-marketplace-validations/ClementWalter_poetry-action

name: Poetry setup
description: Add poetry and install deps with cache
inputs:
  shell:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path .virtualenvs
      shell: ${{shell}}
