# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main", "github-actions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # You may pin to the exact commit or the version.
      # uses: ClementWalter/poetry-action@845abd0cfcc6671c045a2f9df189360bb73e64c4
    - uses: ClementWalter/poetry-action@master
      with:
        os: ubuntu-latest
        python-version: "3.10"
    - name: Install dependencies
      run: |
        poetry install
      shell: bash
    - name: Unit tests
      run:  |
        poetry run task test
      shell: bash
    - name: Lint tests
      run: |
        poetry run task lint
      shell: bash
    - name: Formatter tests
      run: |
        poetry run task formatter
      shell: bash
    - name: Security tests
      run: |
        poetry run task security
      shell: bash

  run:
  
    runs-on: ubuntu-latest

    steps:
      - name: Run the application
        run: |
          poetry run task local
        shell: bash
