# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./example-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs-2/example-app/.venv
        key: ${{ runner.os }}-venv
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # You may pin to the exact commit or the version.
      # uses: ClementWalter/poetry-action@845abd0cfcc6671c045a2f9df189360bb73e64c4
      # modified
    - uses: ./.github/actions/install-poetry
      with:
        os: ubuntu-latest
        python-version: "3.10"

  lint:

    needs: build

    runs-on: ubuntu-latest

    concurrency:
      group: static-tests

    steps:
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs-2/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Lint tests
      run: poetry run task lint


  formatter:

    runs-on: ubuntu-latest

    needs: build

    concurrency:
      group: static-tests

    steps:
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs-2/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Formatter tests
      run: poetry run task formatter


  security:

    runs-on: ubuntu-latest

    needs: build

    concurrency:
      group: static-tests

    steps:
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs-2/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Security tests
      run: poetry run task security


  unittests:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs-2/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Unit tests
      run: poetry run task test
